### ISSUE TITLE
how to import into ES6 module?

### ISSUE THREAD

**Issue by jric** [Eyal-Shalev/docopt.js#12]
import { default as docopt } from '@eyalsh/docopt';
let options = docopt(doc);

results in TypeError: docopt is not a function

Is there an easy way to use this package in an ES6 context?  If there is, maybe it could be added to the README.

**Comment by Eyal-Shalev** [comment]
```
import { default as docopt } from '@eyalsh/docopt';``
```

Is incorrect, use:

```
import docopt from '@eyalsh/docopt';
```
